import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import Module,{createRequire} from 'node:module';
import {assembleV16Page,loadJevV16Page} from '../lib/jevbench-page-v16.mjs';
import {v16CapView} from '../lib/jevbench-presentation-v16.mjs';
const require=createRequire(import.meta.url),React=require('react'),ts=require('typescript');
const {renderToStaticMarkup}=require('react-dom/server'),H='a'.repeat(64);
// Explicit fixture=true; never masquerades as admitted production data.
function fixture(){
 const ds=[{key:'one',label:'One',covers:'Synthetic',n:10,public:5,sealed:5,low_n:false},{key:'two',label:'Two',covers:'Synthetic',n:10,public:5,sealed:5,low_n:false},{key:'three',label:'Three',covers:'Synthetic',n:10,public:5,sealed:5,low_n:false}];
 const hashes=Object.fromEntries(['registry','release','bindings','categories','languages'].map(k=>[k,H]));
 const rows=Array.from({length:116},(_,i)=>({key:`synthetic-${i}`,display:`Synthetic ${i}`,status:i<2?'current':'unmeasured',ranked:i<2,catalogue:{},registration:{lane:i===1?'api':'selfhosted',endpoint_kind:'synthetic',support:{choice:'yes',noul:'yes',score:'yes'},author:null},measurement:i<2?{status:'current',model_version:'v',model_pin:'pin',measured_on:'2000-01-01',measurement_revision:'v1.6.0',method_version:'method',serving:{lane:i===1?'api':'selfhosted'}}:null,axes:{intelligence:80,calibration:60,speed:70,cost:80},composite:i<2?60+i:null,capability:i<2?70:null,headline_eligible:i<2,eligibility_reasons:[],cost:{kind:i<2?'estimate':'unpriced',usd_per_1000:i<2?.1:null,cost_rank_eligible:i<2,admission_sha256:i<2?H:null,basis:'synthetic',bars:i<2?[{role:'served_cost',usd_per_1000:.1,kind:'estimate',basis:'synthetic',ranking_eligible:true},{role:'base_model_reference',usd_per_1000:.2,kind:'estimate',basis:'synthetic base',ranking_eligible:false}]:[]},speed:i<2?{p50_s_adjusted:.2,p50_s_raw:.21,p95_s_raw:.3,n:600}:null,categories:null,language:i<2?{name:'synthetic',model_version:'v',deployment:i===1?'api':'owned',public:{en:{status:'measured',n:30,expected_n:30,non_ok_n:0,cc:75,accuracy:.8,measured_on:'2000-01-02',reason:null,n_by_type:{choice:30},low_n:false}},sealed:{en:{status:'unavailable',n:0,expected_n:0,non_ok_n:0,cc:null,accuracy:null,measured_on:null,reason:'unavailable',n_by_type:{},low_n:true}},carried_base:null}:null,historical_price:i===3?{kind:'estimate',usd_per_1000:.03,basis:'oldmethod dated cost'}:null}));
 const projection={revision:'v1.6.0',fixture:true,catalogue_count:116,reference:{key:'jev-1.13.0',usd_per_1000:.1,p50_s_adjusted:.2,cost_factor:2,latency_factor:2},rows,source_hashes:hashes,category_descriptors:{topics:ds,usecases:ds,languages:ds},composite_order:['synthetic-1','synthetic-0'],capability_order:['synthetic-0','synthetic-1']};
 const cells=Object.fromEntries(ds.map(d=>[d.key,{n:10,public:5,sealed:5,low_n:false,competence:70,score:70}]));
 for(const row of rows.slice(0,2))row.categories={kind:'current',topics:structuredClone(cells),usecases:structuredClone(cells)};
 const profiles=Object.fromEntries(rows.slice(0,2).map(r=>[r.key,{kind:'current',model_version:'v',model_pin:'pin',main_measured_on:'2000-01-01',measured_on:'2000-01-01',revision:'v1.6.0',metric:'equal-present-types',scope:r.registration.lane==='api'?'A300+P300':'S1200+P300',equated:false,source_sha256:H,topics:structuredClone(cells),usecases:structuredClone(cells)}]));
 const scores={'synthetic-0':60,'synthetic-1':61};
 const manifest={kind:'jevbench-v16-page',schema_version:1,fixture:true,generated_on:'2000-01-03',projection_hashes:hashes,expected_catalogue_keys:rows.map(r=>r.key),category_profiles_sha256:H,method:Array.from({length:6},(_,i)=>`Actual synthetic method paragraph ${i}`),rotation:{sealed_release_count:1200,sealed_reserve_count:6000,retire_after_uses:3,api_every_n_releases:3,disclosure:'Synthetic rotation only'},whatif_scorer_sha256:H,official_scenario:'official',scenarios:[{id:'official',label:'Official',source_sha256:H,scorer_sha256:H,weights:{intelligence:1,calibration:1,speed:1,cost:1},scores},{id:'test',label:'Stored test preset',source_sha256:H,scorer_sha256:H,weights:{intelligence:2,calibration:1,speed:1,cost:1},scores:{'synthetic-0':59,'synthetic-1':62}}],revisions:[{revision:'v1.5.5',measured_on:'2000-01-01',summary:'Synthetic history',source_sha256:H,href:'/benchmarks/jevbench/v1.5.5'}]};
 return {projection,manifest,profiles};
}
function assemble(f=fixture()){return assembleV16Page(f.projection,f.manifest,f.profiles,{allowFixture:true});}
function compile(file,additional={}){const path=new URL(`../components/${file}`,import.meta.url);const compiled=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true},reportDiagnostics:true});assert.equal(compiled.diagnostics?.filter(d=>d.category===ts.DiagnosticCategory.Error).length??0,0);const mod=new Module(path.pathname);mod.filename=path.pathname;mod.require=s=>{if(['react','react/jsx-runtime'].includes(s))return require(s);if(s in additional)return additional[s];if(s==='../lib/jevbench-presentation-v16.mjs')return require(new URL(s,path).pathname);throw Error(`Unexpected source dependency ${s}`);};mod._compile(compiled.outputText,path.pathname);return mod.exports;}
const radar=compile('JevRadars.tsx'),component=compile('JevBenchV16ReleasePage.tsx',{'./JevRadars':radar});
const render=page=>renderToStaticMarkup(React.createElement(component.JevBenchV16ReleasePage,{page,allowFixture:true}));
test('default assembly and component refuse fixture without explicit synthetic-only option',()=>{const f=fixture();assert.throws(()=>assembleV16Page(f.projection,f.manifest,f.profiles));assert.throws(()=>renderToStaticMarkup(React.createElement(component.JevBenchV16ReleasePage,{page:assemble()})));});
test('full component SSR mandatory section order, actual radars/language/table/history',()=>{const html=render(assemble());let previous=-1;for(const id of ['jev16-capability','jev16-bubbles','jev16-composite','jev16-compare','jev16-grid','jev16-method','jev16-history']){const i=html.indexOf(`id="${id}"`);assert(i>previous);previous=i;}assert.match(html,/Synthetic 115/);assert.match(html,/data-bh-jev16-price-striped="true"/);assert.match(html,/uc1.1 Choice only/);assert.match(html,/Stored values and sample counts/);assert.match(html,/What If weights/);});
test('missing ranked profile refuses instead of dropping a carried model',()=>{const f=fixture();delete f.profiles['synthetic-1'];assert.throws(()=>assemble(f));});
test('different version or pin profile refuses',()=>{for(const field of ['model_version','model_pin','main_measured_on']){const f=fixture();f.profiles['synthetic-0'][field]='wrong';assert.throws(()=>assemble(f));}});
test('API/local category scope mismatch refuses and no equating accepted',()=>{for(const change of [{scope:'S1200+P300'},{equated:true}]){const f=fixture();Object.assign(f.profiles['synthetic-1'],change);assert.throws(()=>assemble(f));}});
test('explicit dated carry profile retains old metric and scope without relabelling current',()=>{const f=fixture(),r=f.projection.rows[0];r.status='carry';r.measurement.status='carry';r.measurement.measurement_revision='v1.5.5';Object.assign(f.profiles[r.key],{kind:'carry',revision:'v1.5.5',metric:'item-weighted multiusecase',scope:'original v1.5 cohort'});const html=render(assemble(f));assert.match(html,/item-weighted multiusecase/);assert.match(html,/original v1.5 cohort/);assert.match(html,/Carried 2000-01-01/);});
test('missing or future profile date and year zero refuse',()=>{for(const date of [null,'2001-01-01','0000-01-01']){const f=fixture();f.profiles['synthetic-0'].measured_on=date;assert.throws(()=>assemble(f));}});
test('official WhatIf scenario must equal actual stored Composite for every ranked model',()=>{const f=fixture();f.manifest.scenarios[0].scores['synthetic-0']=99;assert.throws(()=>assemble(f));});
test('partial scenario/missing scorer pin refuses; no harmonic reconstruction fallback',()=>{const f=fixture();delete f.manifest.scenarios[1].scores['synthetic-1'];assert.throws(()=>assemble(f));const g=fixture();g.manifest.scenarios[1].scorer_sha256='b'.repeat(64);assert.throws(()=>assemble(g));});
test('catalogue continuity requires all116 exact keys',()=>{const f=fixture();f.manifest.expected_catalogue_keys.pop();assert.throws(()=>assemble(f));});
test('caps share exact eligibility and never substitute Speed axis for null median',()=>{const f=fixture();f.projection.rows[0].speed.p50_s_adjusted=null;const page=assemble(f);const view=v16CapView(page.projection,undefined,{allowFixture:true});assert(!view.eligible.some(x=>x.row.key==='synthetic-0'));assert(view.outside.find(x=>x.row.key==='synthetic-0').reasons.includes('Measured adjusted median unavailable.'));});
test('missing language and unknown rotation refuse full page',()=>{const f=fixture();f.projection.rows[0].language=null;assert.throws(()=>assemble(f));const g=fixture();g.manifest.rotation.api_every_n_releases=null;assert.throws(()=>assemble(g));});
test('loader refuses expected projection hash mismatch before aggregate assembly',async()=>{await assert.rejects(()=>loadJevV16Page({projectionInput:{registry:{sha256:'b'.repeat(64)}},expected:{as_of:'2000-01-03',projection:{registry:H},pageManifest:H,categoryProfiles:H}}));});

test('current profile values must equal projection category values, not caller substitutes',()=>{const f=fixture();f.profiles['synthetic-0'].topics.one.competence=99;assert.throws(()=>assemble(f));});

const digest=s=>createHash('sha256').update(s).digest('hex');
const invalidLoad=(raw,expectedHash=digest(raw))=>({projectionInput:Object.fromEntries(['registry','release','bindings','categories','languages'].map(k=>[k,{sha256:H}])),pageManifest:{raw,sha256:expectedHash},categoryProfiles:{raw:'{}',sha256:digest('{}')},expected:{as_of:'2000-01-03',projection:Object.fromEntries(['registry','release','bindings','categories','languages'].map(k=>[k,H])),pageManifest:expectedHash,categoryProfiles:digest('{}')}});
test('first stored page parser rejects nested duplicate keys before projection',async()=>{await assert.rejects(()=>loadJevV16Page(invalidLoad('{"nested":{"cost":120,"cost":0}}')));});
test('byte identity fails before parsing/normalization; nonfinite raw numbers rejected',async()=>{await assert.rejects(()=>loadJevV16Page(invalidLoad('{}',H)));await assert.rejects(()=>loadJevV16Page(invalidLoad('{"number":1e999}')));});
test('page generated day cannot exceed authenticated server as-of bound',async()=>{const f=fixture(),raw=JSON.stringify({...f.manifest,generated_on:'2001-01-01',category_profiles_sha256:digest('{}')});await assert.rejects(()=>loadJevV16Page(invalidLoad(raw)));});

// R2: accepted raw chance-corrected competence may be negative. Geometry alone clips.
function rawCell(f,key,dimension,value){const c=f.profiles[key][dimension].one;c.competence=value;c.score=value===null?null:Math.max(0,Math.min(100,value));f.projection.rows.find(r=>r.key===key).categories[dimension].one=structuredClone(c);}
test('finite negative current competence passes exact profile binding and stays raw in real SSR table',()=>{const f=fixture();rawCell(f,'synthetic-0','topics',-25);const before=JSON.stringify(f);const page=assemble(f),html=render(page);assert.equal(page.profiles['synthetic-0'].topics.one.competence,-25);assert.match(html,/<td>-25\.00<\/td>/);assert.equal(JSON.stringify(f),before);const topicSvg=html.match(/<svg[^>]*viewBox="0 0 560 520"[\s\S]*?<\/svg>/)[0];assert.match(topicSvg,/<circle cx="280" cy="264"/);assert.doesNotMatch(topicSvg,/<circle cx="280" cy="300\.25"/);});
test('finite raw upper value remains raw while only category radar coordinate clips100',()=>{const f=fixture();rawCell(f,'synthetic-0','topics',125);const html=render(assemble(f));assert.match(html,/<td>125\.00<\/td>/);const topicSvg=html.match(/<svg[^>]*viewBox="0 0 560 520"[\s\S]*?<\/svg>/)[0];assert.match(topicSvg,/<circle cx="280" cy="119"/);});
test('language negative competence keeps native value and clips only owned page geometry',()=>{const f=fixture();f.projection.rows[0].language.public.en.cc=-7;const html=render(assemble(f));assert.match(html,/<td>-7\.00<\/td>/);const languageSvg=html.match(/<svg[^>]*viewBox="0 0 680 650"[\s\S]*?<\/svg>/)[0];assert.match(languageSvg,/<circle cx="340" cy="329"/);});
test('null and low-n cells remain unavailable or omitted, no geometry fakezero',()=>{const f=fixture();for(const dimension of ['topics','usecases']){rawCell(f,'synthetic-0',dimension,null);const c=f.profiles['synthetic-0'][dimension].one;c.n=0;c.low_n=true;f.projection.rows[0].categories[dimension].one=structuredClone(c);}const page=assemble(f),html=render(page);assert.equal(page.profiles['synthetic-0'].topics.one.competence,null);const topicSvg=html.match(/<svg[^>]*viewBox="0 0 560 520"[\s\S]*?<\/svg>/)[0];assert.doesNotMatch(topicSvg,/<circle cx="280" cy="264"/);assert.match(html,/<td>Unavailable<\/td><td>0 \(low n\)/);});
test('nonfinite raw competence rejected without geometry normalization',()=>{for(const value of [NaN,Infinity,-Infinity]){const f=fixture();rawCell(f,'synthetic-0','topics',value);assert.throws(()=>assemble(f));}});
test('negative value cannot bypass current profile exact match',()=>{const f=fixture();f.profiles['synthetic-0'].topics.one.competence=-25;assert.throws(()=>assemble(f));});

test('two synchronized Capability charts use actual metric axes and the same eligible models',()=>{const f=fixture();f.projection.rows[0].speed.p50_s_adjusted=.3;const html=render(assemble(f));for(const axis of ['cost','latency']){const svg=html.match(new RegExp(`<svg[^>]*data-bh-jev16-capability-plot="${axis}"[\\s\\S]*?<\\/svg>`))[0];assert.match(svg,/Capability Score/);for(const key of ['synthetic-0','synthetic-1'])assert.match(svg,new RegExp(`data-bh-jev16-plot-model="${key}"`));}assert.match(html,/Measured adjusted median latency \(seconds\)/);assert.match(html,/Served cost \(USD\/1000\)/);assert.match(html,/median latency \(seconds\) 0.3, Capability 70/);assert.match(html,/Show 3D/);});
test('both charts omit an ineligible finite-cost model rather than plotting its uncapped capability',()=>{const f=fixture();f.projection.rows[0].cost.cost_rank_eligible=false;const html=render(assemble(f));const charts=[...html.matchAll(/<svg[^>]*data-bh-jev16-capability-plot="[^"]+"[\s\S]*?<\/svg>/g)];assert.equal(charts.length,2);for(const [svg] of charts){assert.doesNotMatch(svg,/data-bh-jev16-plot-model="synthetic-0"/);assert.match(svg,/data-bh-jev16-plot-model="synthetic-1"/);}});
test('Composite bars render exact stored official scores and retain raw numbers',()=>{const html=render(assemble());assert.match(html,/data-bh-jev16-composite-bar="synthetic-1" data-bh-jev16-stored-score="61" style="width:61%"/);assert.match(html,/Synthetic 1 · 61.00/);assert.match(html,/data-bh-jev16-composite-bar="synthetic-0" data-bh-jev16-stored-score="60" style="width:60%"/);});
test('unknown model size and context remain explicit full-table columns',()=>{const html=render(assemble());assert.match(html,/<th>Size<\/th><th>Context<\/th>/);assert.match(html,/<td>Unavailable<\/td><td>Unavailable<\/td>/);});
