import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module,{createRequire} from 'node:module';
import {createHash,webcrypto} from 'node:crypto';
import {projectJevV16Registry,canonicalV16Aggregate} from '../lib/jevbench-registry-v16.mjs';
import {projectJevV16RegistryWithCarry} from '../lib/jevbench-registry-v16-carry.mjs';
import {validateDatedCarryArtifact,datedCarryForBinding} from '../lib/jevbench-dated-carry-v16.mjs';
import {assembleV16PageWithCarry,loadJevV16PageWithCarry} from '../lib/jevbench-page-v16-carry.mjs';
import {parseV16PageView,serializeV16PageView,normalizeV16PageView,bindV16PageHistory} from '../lib/jevbench-page-v16-url.mjs';
import {categoryFixture} from './jevbench-category-fixture-v16.mjs';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
// ALL values synthetic fixture=true; no real lineage/source/runtime grants.
const H = c => c.repeat(64);
const digest = raw => createHash('sha256').update(raw).digest('hex');
const store = v => { const raw = JSON.stringify(v); return { raw, sha256: digest(raw) }; };
const keys = ['synthetic-a', 'synthetic-b'];
function languageFixture() {
  const languages = ['ar', 'da', 'zh-Hans', ...Array.from({ length: 19 }, (_, i) => `synthetic-${i}`)].map(key => ({ key, label: `Synthetic ${key}`, sealed_n: ['ar', 'da', 'zh-Hans'].includes(key) ? 40 : 30, public_n: ['ar', 'da', 'zh-Hans'].includes(key) ? 40 : 30, native_review_basis: 'Synthetic; no actual labels or review.' }));
  const row = (api) => ({ name: 'Synthetic only', deployment: api ? 'api' : 'owned', model_version: 'synthetic-version', public_scope_sha256: H('b'), sealed_scope_sha256: api ? null : H('c'),
    public: Object.fromEntries(languages.map(l => [l.key, { status: 'measured', n: l.public_n, expected_n: l.public_n, non_ok_n: 1, cc: -7, accuracy: .25, measured_on: '2000-01-02', reason: null, n_by_type: { choice: l.public_n }, low_n: false }])),
    sealed: Object.fromEntries(languages.map(l => [l.key, api ? { status: 'unavailable', n: 0, expected_n: 0, non_ok_n: 0, cc: null, accuracy: null, measured_on: null, reason: 'API public-only.', n_by_type: {}, low_n: true } : { status: 'measured', n: l.sealed_n, expected_n: l.sealed_n, non_ok_n: 0, cc: -2, accuracy: .3, measured_on: '2000-01-02', reason: null, n_by_type: { choice: l.sealed_n }, low_n: false }])), carried_base: null });
  return { kind: 'language-diagnostics', schema_version: 1, benchmark: 'jevbench', revision: 'v1.6.0', supplement_id: 'v1.6.0-uc1.1', basis: 'uc1.1 Choice only', fixture: true, generated_utc: '2000-01-03T00:00:00Z', pool_manifest_sha256: H('b'), method: { version: 'synthetic', source_sha256: H('c'), description: 'Synthetic only' }, languages, systems: { 'synthetic-a': row(false), 'synthetic-b': row(true) } };
}
function parts() {
  const allKeys = [...keys, ...Array.from({ length: 113 }, (_, i) => `unmeasured-${i}`), 'fastino-gliner-2-5-decide'];
  const absent = allKeys.slice(112, 115);
  const registry = { source_status: 'INACTIVE_SOURCE_CANDIDATE', public_roster_count: 115, public_sha256: H('d'),
    catalogue: Object.fromEntries(allKeys.map(key => [key, { display: `Synthetic ${key}`, author: 'Synthetic author', historical_cost: { kind: 'estimate', usd_per_1000: .03, basis: 'Historical synthetic per1000 estimate.' }, historical_price_scenario: null }])),
    scorer_registry: Object.fromEntries(allKeys.filter(k => !absent.includes(k)).map(key => [key, { display: `Synthetic ${key}`, lane: key === 'synthetic-b' || key === 'fastino-gliner-2-5-decide' ? 'api' : 'selfhosted', endpoint_kind: key === 'synthetic-b' || key === 'fastino-gliner-2-5-decide' ? 'api' : 'own-server', author: 'Synthetic author', support: { choice: 'confidence', noul: 'confidence', score: 'confidence' } }])), pending_scorer_metadata_keys: absent };
  const categories = categoryFixture(), languages = languageFixture();
  const systems = keys.map((key, i) => ({ key, display: `Synthetic ${key}`, endpoint_kind: i ? 'api' : 'own-server', api_flag: !!i, ranked: true, full_coverage: true, status: { status: 'complete' }, axes: { intelligence: 80 + i * 10, calibration: 60 + i * 10, speed: 70, cost: 80 }, capability: 70 + i * 10, jevbench_score: 65 + i, cost: { kind: 'estimate', usd_per_1000: .1, basis: 'Disclosed synthetic carry cost; not billing.' }, speed: { n: i ? 600 : 1500, p50_s_raw: .2, p50_s_adjusted: .3, adjustment: i ? 'none (API)' : 'x2 + .15 assumption' }, v16: { lane: i ? 'api' : 'selfhosted', n_items: i ? 600 : 1500, n_public: 300, n_sealed_side: i ? 300 : 1200, complete: true } }));
  const rows = Object.fromEntries(keys.map((key, i) => [key, { key, status: 'current', measurement_revision: 'v1.6.0', method_version: 'synthetic-v16', model_version: 'synthetic-version', model_pin: `synthetic-pin-${i}`, measured_on: i ? '2000-01-02' : '2000-01-01', origin_sha256: H('e'), score_row_sha256: H('e'), scorer_sha256: H('a'), cohort_sha256: H('a'), serving: { lane: i ? 'api' : 'selfhosted', endpoint_kind: i ? 'api' : 'own-server', endpoint_condition: null, api_flag: !!i }, cost_rank_eligible: true, cost_admission_sha256: H('f') }]));
  return { registry, categories, languages, systems, rows, ref: { key: 'synthetic-a', usd_per_1000: .1, p50_s_adjusted: .3, cost_factor: 2, latency_factor: 2, source_sha256: H('a') } };
}
function input(p = parts()) {
  const registry = store(p.registry), categories = store(p.categories), languages = store(p.languages), origins = {};
  for (const row of p.systems) {
    const b = p.rows[row.key]; b.score_row_sha256 = digest(canonicalV16Aggregate(row));
    const origin = store({ kind: 'jevbench-measurement-origin', ...Object.fromEntries(['key', 'measurement_revision', 'method_version', 'model_version', 'model_pin', 'measured_on', 'scorer_sha256', 'cohort_sha256', 'serving'].map(k => [k, b[k]])) }); b.origin_sha256 = origin.sha256; origins[origin.sha256] = origin;
  }
  const referenceOrigin = store({ kind: 'jevbench-frozen-capability-reference', key: p.ref.key, model_version: 'synthetic-reference-version', model_pin: null, measurement_revision: 'synthetic-historic-reference', measured_on: null, ...Object.fromEntries(['usd_per_1000','p50_s_adjusted','cost_factor','latency_factor'].map(k => [k, p.ref[k]])) }); p.ref.source_sha256 = referenceOrigin.sha256; origins[referenceOrigin.sha256] = referenceOrigin;
  const release = store({ benchmark: 'JevBench', revision: 'v1.6.0', protocol: 'jevbench::v1.6', systems: p.systems, board: { capability: { order: [...keys].reverse() } }, projection: { schema_version: 1, fixture: true, generated_on: '2000-01-03', registry_sha256: registry.sha256, scorer_sha256: H('a'), method_version: 'synthetic-v16', category_sha256: categories.sha256, language_sha256: languages.sha256, category_provenance: p.categories.provenance, capability_reference: p.ref } });
  const bindings = store({ kind: 'jevbench-measurement-bindings', revision: 'v1.6.0', release_sha256: release.sha256, public_sha256: p.registry.public_sha256, rows: p.rows, diagnostics: Object.fromEntries(p.systems.filter(r => r.ranked).map(r => { const b = p.rows[r.key]; return [r.key, { key: r.key, model_version: b.model_version, model_pin: b.model_pin, main_measured_on: b.measured_on, category_sha256: categories.sha256, language_sha256: languages.sha256, category_provenance: p.categories.provenance, language_pool_sha256: p.languages.pool_manifest_sha256, language_method_sha256: p.languages.method.source_sha256 }]; })) });
  return { registry, release, bindings, categories, languages, origins };
}

function carryParts(){
 const p=parts(),b=p.rows['synthetic-b'];b.status='carry';b.measurement_revision='v1.5.5';b.method_version='synthetic-old-score-method';b.scorer_sha256=H('9');b.cohort_sha256=H('c');delete p.systems[1].v16;p.systems[1].speed.n=6;delete p.categories.systems['synthetic-b'];delete p.languages.systems['synthetic-b'];
 const taxonomy={topics:[{key:'old-one',label:'Old One',covers:'Old synthetic',n:4,open:1,sealed:3},{key:'old-two',label:'Old Two',covers:'Old synthetic',n:3,open:1,sealed:2},{key:'old-three',label:'Old Three',covers:'Old synthetic',n:3,open:1,sealed:2}],usecases:[{key:'old-use-one',label:'Old Use One',covers:'Multiple synthetic',n:7,open:2,sealed:5},{key:'old-use-two',label:'Old Use Two',covers:'Multiple synthetic',n:6,open:2,sealed:4}]};
 const carry={kind:'jevbench-dated-category-carry',benchmark:'JevBench',revision:'v1.6.0',fixture:true,generated_on:'2000-01-03',public_roster_sha256:p.registry.public_sha256,source_artifact_sha256:H('1'),source_results_sha256:H('2'),taxonomy_sha256:digest(canonicalV16Aggregate(taxonomy)),cohort_sha256:H('c'),projection_source_sha256:H('3'),artifact_revision:'v1.5.5',method_version:'v1.5-item-count-weighted-multiple-usecase',metric:'Old raw item-weighted competence',labelling:'Old synthetic labels',rules:['Original multiusecase labels'],min_n:2,taxonomy,full_cohort:{name:'Original synthetic old pool',n:10,open:3,sealed:7,membership_sha256:H('c')},profiles:{'synthetic-b':{key:'synthetic-b',model_version:b.model_version,model_pin:b.model_pin,measurement_revision:b.measurement_revision,measurement_method_version:b.method_version,main_measured_on:b.measured_on,original_model_revision:'synthetic-original-model-revision',measurement_date:{precision:'calendar-day',value:b.measured_on,timezone:'unknown',source_original:'2 January 2000 (synthetic)',origin_receipt_sha256:H('4')},measurement_descriptor_sha256:H('5'),origin_receipt_sha256:H('4'),row_cohort:{n:6,open:2,sealed:4},cells:{topics:{'old-one':{n:2,competence:-25},'old-two':{n:2,competence:60}},usecases:{'old-use-one':{n:5,competence:20},'old-use-two':{n:5,competence:-10}}}}}};
 return {p,carry};
}
function carryInput(f=carryParts()){
 const i=input(f.p);i.carry=store(f.carry);const bindings=JSON.parse(i.bindings.raw);bindings.carry_diagnostics={};
 for(const b of Object.values(bindings.rows).filter(b=>b.status==='carry')){delete bindings.diagnostics[b.key];const p=f.carry.profiles[b.key]??{...carryParts().carry.profiles['synthetic-b'],...b,main_measured_on:b.measured_on};bindings.carry_diagnostics[b.key]={key:p.key,model_version:p.model_version,model_pin:p.model_pin,main_measured_on:p.main_measured_on,carry_sha256:i.carry.sha256,...Object.fromEntries(['source_artifact_sha256','source_results_sha256','taxonomy_sha256','cohort_sha256'].map(k=>[k,f.carry[k]])),measurement_descriptor_sha256:p.measurement_descriptor_sha256,origin_receipt_sha256:p.origin_receipt_sha256};}
 i.bindings=store(bindings);return i;
}
const project=i=>projectJevV16RegistryWithCarry(i,{allowFixture:true});
function pageParts(projection){
 const profiles=Object.fromEntries(projection.rows.filter(r=>r.ranked).map(r=>[r.key,r.status==='carry'?r.carry_categories:{kind:'current',model_version:r.measurement.model_version,model_pin:r.measurement.model_pin,main_measured_on:r.measurement.measured_on,measured_on:r.measurement.measured_on,revision:'v1.6.0',metric:'Raw current equal present types',scope:r.categories.cohort,equated:false,source_sha256:projection.source_hashes.categories,topics:r.categories.topics,usecases:r.categories.usecases}]));
 const manifest={kind:'jevbench-v16-page',schema_version:1,fixture:true,generated_on:'2000-01-03',projection_hashes:projection.source_hashes,expected_catalogue_keys:projection.rows.map(r=>r.key),category_profiles_sha256:store(profiles).sha256,method:Array.from({length:6},(_,i)=>`Synthetic disclosure ${i}`),rotation:{sealed_release_count:1200,sealed_reserve_count:6000,retire_after_uses:3,api_every_n_releases:3,disclosure:'Synthetic only'},whatif_scorer_sha256:H('a'),official_scenario:'A',scenarios:[{id:'A',label:'Official stored A',source_sha256:H('6'),scorer_sha256:H('a'),weights:{intelligence:1,calibration:1,speed:1,cost:1},scores:Object.fromEntries(projection.rows.filter(r=>r.ranked).map(r=>[r.key,r.composite]))}],revisions:[{revision:'v1.5.5',measured_on:'2000-01-02',summary:'Synthetic',source_sha256:H('7'),href:'/benchmarks/jevbench/v1.5.5'}]};
 return {profiles,manifest};
}
const require=createRequire(import.meta.url),React=require('react'),ts=require('typescript'),{renderToStaticMarkup}=require('react-dom/server');
function compile(file,imports={}){const path=new URL(`../components/${file}`,import.meta.url),c=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true},reportDiagnostics:true});assert.equal(c.diagnostics?.filter(x=>x.category===ts.DiagnosticCategory.Error).length??0,0);const m=new Module(path.pathname);m.filename=path.pathname;m.require=s=>{if(['react','react/jsx-runtime'].includes(s))return require(s);if(s in imports)return imports[s];if(['../lib/jevbench-presentation-v16.mjs','../lib/jevbench-page-v16-url.mjs'].includes(s))return require(new URL(s,path).pathname);throw Error(`Unexpected own source import ${s}`);};m._compile(c.outputText,path.pathname);return m.exports;}
const radars=compile('JevRadars.tsx'),{JevBenchV16CarryReleasePage}=compile('JevBenchV16CarryReleasePage.tsx',{'./JevRadars':radars});
test('original current-only projector refuses carry, NEW distinct projector keeps116 and bothranked exactold/current',async()=>{const i=carryInput(),before=JSON.stringify(i),old={...i};delete old.carry;const oldbindings=JSON.parse(old.bindings.raw);delete oldbindings.carry_diagnostics;old.bindings=store(oldbindings);await assert.rejects(()=>projectJevV16Registry(old,{allowFixture:true}));const out=await project(i),b=out.rows.find(r=>r.key==='synthetic-b');assert.equal(out.rows.length,116);assert.equal(out.rows.filter(r=>r.ranked).length,2);assert.equal(b.categories,null);assert.equal(b.language,null);assert.equal(b.carry_categories.cells.topics['old-one'].competence,-25);assert.equal(b.carry_categories.measurement_date.timezone,'unknown');assert.equal(b.measurement.measured_on,'2000-01-02');assert.equal(b.speed.p50_s_adjusted,.3);assert.equal(b.cost.usd_per_1000,.1);assert.equal(JSON.stringify(i),before);});
test('actual loader→projection→assembly→SSR positive synthetic path preservesold own taxonomy/date and unmeasured catalogue',async()=>{const i=carryInput(),projection=await project(i),{manifest,profiles}=pageParts(projection),manifestStored=store(manifest),profilesStored=store(profiles),page=await loadJevV16PageWithCarry({projectionInput:i,pageManifest:manifestStored,categoryProfiles:profilesStored,expected:{as_of:'2000-01-03',projection:projection.source_hashes,pageManifest:manifestStored.sha256,categoryProfiles:profilesStored.sha256}},{allowFixture:true});const html=renderToStaticMarkup(React.createElement(JevBenchV16CarryReleasePage,{page,allowFixture:true}));assert.match(html,/Old One/);assert.match(html,/-25\.00/);assert.match(html,/2 January 2000/);assert.match(html,/timezone unknown/);assert.match(html,/whole pool, not row split/);assert.match(html,/historical carry/);assert.match(html,/Synthetic unmeasured-112/);assert.equal(page.profiles['synthetic-b'].cells.topics['old-three'],undefined);});
test('production defaults reject synthetic carry fixture',async()=>{await assert.rejects(()=>projectJevV16RegistryWithCarry(carryInput()));});
for(const [name,change]of [
 ['missingolderprofile',f=>{delete f.carry.profiles['synthetic-b'];}],
 ['wrongoldmodelpin',f=>{f.carry.profiles['synthetic-b'].model_pin='wrong';}],
 ['wrongmodelversion',f=>{f.carry.profiles['synthetic-b'].model_version='wrong';}],
 ['privatecurrentversionmasqueradingold',f=>{f.carry.profiles['synthetic-b'].measurement_revision='v1.6.0';}],
 ['futuredatetime',f=>{f.carry.profiles['synthetic-b'].measurement_date.value='2000-01-04';}],
 ['yearzero',f=>{f.carry.profiles['synthetic-b'].measurement_date.value='0000-01-02';}],
 ['fakemidnightprecision',f=>{f.carry.profiles['synthetic-b'].measurement_date.value='2000-01-02T00:00:00Z';}],
 ['UTCwithunknowntimezone',f=>{Object.assign(f.carry.profiles['synthetic-b'].measurement_date,{precision:'utc-instant',value:'2000-01-02T12:00:00Z'});}],
 ['crossedoriginreceipt',f=>{f.carry.profiles['synthetic-b'].measurement_date.origin_receipt_sha256=H('f');}],
 ['cellboolean',f=>{f.carry.profiles['synthetic-b'].cells.topics['old-one'].n=true;}],
 ['inventedcategoryrowsplit',f=>{f.carry.profiles['synthetic-b'].cells.topics['old-one'].public=1;}],
 ['falsecurrentmetricmethod',f=>{f.carry.method_version='v1.6-equal-present-type';}],
 ['extraunboundmodel',f=>{f.carry.profiles.unknown=structuredClone(f.carry.profiles['synthetic-b']);f.carry.profiles.unknown.key='unknown';}],
 ['falsepublicroster',f=>{f.carry.public_roster_sha256=H('e');}],
 ['invalidtopicglobalcount',f=>{f.carry.taxonomy.topics[0].n=5;}],
 ['oversizedrowcell',f=>{f.carry.profiles['synthetic-b'].cells.topics['old-one'].n=7;}],
 ['disjointsumoversized',f=>{f.carry.profiles['synthetic-b'].cells.topics['old-one'].n=4;f.carry.profiles['synthetic-b'].cells.topics['old-two'].n=3;}],
])test(`hold ${name}`,async()=>{const f=carryParts();change(f);await assert.rejects(()=>project(carryInput(f)));});
test('multiple-usecase sum may exceedrow total withoutchangingraw values',async()=>{const out=await project(carryInput()),c=out.rows.find(r=>r.key==='synthetic-b').carry_categories;assert.equal(Object.values(c.cells.usecases).reduce((s,x)=>s+x.n,0),10);assert.equal(c.row_cohort.n,6);assert.equal(c.cells.usecases['old-use-two'].competence,-10);});
test('current projection/cells remain exact acceptedcurrent contract',async()=>{const out=await project(carryInput()),a=out.rows.find(r=>r.key==='synthetic-a');assert.equal(a.carry_categories,null);assert.equal(a.categories.cohort,'S1200+P300');assert.equal(a.categories.topics['synthetic-0'].competence,-12.5);assert.equal(a.language.public.ar.cc,-7);});
test('missingpagecarryprofile ishold not40rowdrop',async()=>{const out=await project(carryInput()),{manifest,profiles}=pageParts(out);delete profiles['synthetic-b'];assert.throws(()=>assembleV16PageWithCarry(out,manifest,profiles,{allowFixture:true}));});
test('carryhash/oldtaxonomy/diagnosticbytejoin failclosed',async()=>{for(const field of ['carry_sha256','measurement_descriptor_sha256','origin_receipt_sha256','source_results_sha256']){const i=carryInput(),b=JSON.parse(i.bindings.raw);b.carry_diagnostics['synthetic-b'][field]=H('f');i.bindings=store(b);await assert.rejects(()=>project(i));}const f=carryParts();f.carry.taxonomy_sha256=H('f');await assert.rejects(()=>project(carryInput(f)));});
test('negative/nonfinite nevernormalize; duplicatefirstJSON fails',async()=>{const i=carryInput();i.carry.raw=i.carry.raw.replace('"competence":-25','"competence":-25,"competence":0');i.carry.sha256=digest(i.carry.raw);await assert.rejects(()=>project(i));const f=carryParts();f.carry.profiles['synthetic-b'].cells.topics['old-one'].competence=Infinity;assert.throws(()=>validateDatedCarryArtifact(f.carry));});
test('costandactualmedianeligibility remain mandatory despiteoldprofile',async()=>{const f=carryParts();f.p.rows['synthetic-b'].cost_rank_eligible=false;f.p.rows['synthetic-b'].cost_admission_sha256=null;await assert.rejects(()=>project(carryInput(f)));const g=carryParts();g.p.systems[1].speed.p50_s_adjusted=null;const out=await project(carryInput(g));assert(!out.capability_order.includes('synthetic-b'));assert.equal(out.rows.find(r=>r.key==='synthetic-b').axes.speed,70);});

test('own SVG scatter coordinates and logarithmictraffic widths round3 for SSR stability',async()=>{const f=carryParts();f.p.systems[0].cost.usd_per_1000=.133333333333;f.p.systems[0].speed.p50_s_adjusted=.233333333333;const projection=await project(carryInput(f)),{manifest,profiles}=pageParts(projection),page=assembleV16PageWithCarry(projection,manifest,profiles,{allowFixture:true});const html=renderToStaticMarkup(React.createElement(JevBenchV16CarryReleasePage,{page,allowFixture:true}));for(const [,value]of [...html.matchAll(/<g[^>]*data-bh-jev16-plot-model=[^>]*>([\s\S]*?)<\/g>/g)].flatMap(m=>[...m[1].matchAll(/(?:cx|cy|x|y)="(-?\d+(?:\.\d+)?)"/g)]))assert((value.split('.')[1]??'').length<=3);for(const [,value]of html.matchAll(/width:(-?\d+(?:\.\d+)?)%/g))assert((value.split('.')[1]??'').length<=3);assert.match(html,/data-bh-jev16-plot-model="synthetic-a"/);});

test('all forty historical ranked rows retained alongside current and complete116 catalogue',async()=>{
 const f=carryParts();for(let j=0;j<39;j++){const key=`unmeasured-${j}`,b=structuredClone(f.p.rows['synthetic-b']),r=structuredClone(f.p.systems[1]),p=structuredClone(f.carry.profiles['synthetic-b']);b.key=r.key=p.key=key;b.model_pin=p.model_pin=`old-synthetic-pin-${j}`;r.display=f.p.registry.catalogue[key].display;f.p.registry.scorer_registry[key].lane='api';f.p.registry.scorer_registry[key].endpoint_kind='api';f.p.rows[key]=b;f.p.systems.push(r);f.carry.profiles[key]=p;}
 const projection=await project(carryInput(f));assert.equal(projection.rows.length,116);assert.equal(projection.rows.filter(r=>r.ranked).length,41);assert.equal(projection.rows.filter(r=>r.carry_categories).length,40);const {manifest,profiles}=pageParts(projection),page=assembleV16PageWithCarry(projection,manifest,profiles,{allowFixture:true});assert.equal(Object.keys(page.profiles).length,41);const html=renderToStaticMarkup(React.createElement(JevBenchV16CarryReleasePage,{page,allowFixture:true}));assert.match(html,/Synthetic unmeasured-38/);delete profiles['unmeasured-38'];assert.throws(()=>assembleV16PageWithCarry(projection,manifest,profiles,{allowFixture:true}));
});

function urlManifest(){return {official_scenario:'A',scenarios:[{id:'A'},{id:'B'}]};}
test('SSR supplied URL caps and stored scenario render explicitly nonofficial without window',async()=>{
 const projection=await project(carryInput()),{manifest,profiles}=pageParts(projection);manifest.scenarios.push({...structuredClone(manifest.scenarios[0]),id:'B',label:'Stored B',weights:{intelligence:2,calibration:1,speed:1,cost:1}});const page=assembleV16PageWithCarry(projection,manifest,profiles,{allowFixture:true});
 const html=renderToStaticMarkup(React.createElement(JevBenchV16CarryReleasePage,{page,allowFixture:true,initialSearch:'?costcap=3.25&latcap=off&jevscenario=B'}));assert.match(html,/Custom caps — not the official ranking/);assert.match(html,/What If — stored scorer scenario, not official ranking/);assert.match(html,/3.25×/);assert.match(html,/Median latency cap: off/);assert.match(html,/Original date precision: calendar-day; timezone unknown/);
 const defaults=renderToStaticMarkup(React.createElement(JevBenchV16CarryReleasePage,{page,allowFixture:true,initialSearch:'?costcap=NaN&latcap=99&jevscenario=unknown&intelligence_weight=999'}));assert.match(defaults,/Official 2× envelope/);assert.match(defaults,/Official stored Composite/);assert.doesNotMatch(defaults,/What If — stored scorer scenario/);assert.equal(page.manifest.scenarios.length,2);
});
test('URL strict bounds malformed duplicate unknown values fall back independently',()=>{
 const m=urlManifest();for(const v of ['NaN','Infinity','-1','0','10.01','2e0','2x','%ZZ','', 'true'])assert.equal(parseV16PageView('?costcap='+v,m).caps.costFactor,2);
 assert.deepEqual(parseV16PageView('?costcap=3&costcap=4&latcap=1&jevscenario=B&jevscenario=A',m),{caps:{costFactor:2,latencyFactor:1},scenario:'A'});
 assert.deepEqual(parseV16PageView('?costcap=1&latcap=10&jevscenario=B',m),{caps:{costFactor:1,latencyFactor:10},scenario:'B'});assert.equal(parseV16PageView('?costcap=none',m).caps.costFactor,Infinity);assert.equal(parseV16PageView('?costcap=off',m).caps.costFactor,Infinity);
 assert.deepEqual(normalizeV16PageView({caps:{costFactor:true,latencyFactor:-Infinity},scenario:'new'},m),{caps:{costFactor:2,latencyFactor:2},scenario:'A'});
});
test('URL serialization preserves unrelated query reset removes only owned fields and exact fractional caps roundtrip',()=>{
 const m=urlManifest(),value={caps:{costFactor:2.25,latencyFactor:Infinity},scenario:'B'};const q=serializeV16PageView('?filter=keep&costcap=bad&jevscenario=unknown',value,m);assert.equal(new URLSearchParams(q).get('filter'),'keep');assert.deepEqual(parseV16PageView(q,m),value);
 const reset=serializeV16PageView(q,{caps:{costFactor:2,latencyFactor:2},scenario:'A'},m);assert.equal(reset,'filter=keep');
});
test('actual history binding mount update popstate reset disposal uses current URL and stored allowlist',()=>{
 let location=new URL('https://example.invalid/jev-models?filter=keep&costcap=3&jevscenario=B#compare'),listener=null,updates=[],states=[];
 const browser={get location(){return location;},history:{state:{original:true},replaceState(state,unused,url){assert.deepEqual(state,{original:true});assert.equal(unused,'');location=new URL(url);updates.push(url);}},addEventListener(event,fn){assert.equal(event,'popstate');listener=fn;},removeEventListener(event,fn){assert.equal(event,'popstate');assert.equal(listener,fn);listener=null;}};
 const h=bindV16PageHistory(browser,urlManifest(),s=>states.push(s));assert.deepEqual(states.at(-1),{caps:{costFactor:3,latencyFactor:2},scenario:'B'});
 h.update({caps:{costFactor:Infinity,latencyFactor:1},scenario:'B'});assert.equal(location.hash,'#compare');assert.equal(location.searchParams.get('filter'),'keep');assert.equal(location.searchParams.get('costcap'),'off');assert.equal(updates.length,1);
 location=new URL('https://example.invalid/jev-models?costcap=10&latcap=4&jevscenario=A');listener();assert.deepEqual(states.at(-1),{caps:{costFactor:10,latencyFactor:4},scenario:'A'});assert.equal(updates.length,1);
 location=new URL('https://example.invalid/jev-models?costcap=bad&jevscenario=not-admitted');listener();assert.deepEqual(states.at(-1),{caps:{costFactor:2,latencyFactor:2},scenario:'A'});
 h.update({caps:{costFactor:2,latencyFactor:2},scenario:'A'});assert.equal(location.search,'');const old=states.length;h.dispose();assert.equal(listener,null);h.update({caps:{costFactor:4,latencyFactor:4},scenario:'B'});assert.equal(states.length,old);
});
