import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require('/opt/tao-head-family-video-render-v1/node_modules/playwright');
const out='ops/rebuild-2026-09/evidence/phase-07/rendered';fs.mkdirSync(out,{recursive:true});
const base=process.env.BH_CHECK_BASE||'http://127.0.0.1:3317';const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await ctx.addInitScript(()=>{try{localStorage.setItem('bh-theme','light')}catch{}});
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
async function snap(name,path,width,height,theme){await page.setViewportSize({width,height});await page.goto(base+path);await page.waitForLoadState('networkidle');if(theme==='dark')await page.getByRole('button',{name:'Toggle color theme'}).click();await page.screenshot({path:out+'/'+name+'.png'});await page.addScriptTag({path:'/tmp/postial-mail-node-modules-copy-1867145/axe-core/axe.min.js'});const a=await page.evaluate(async()=>{const x=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}});return {violations:x.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),incomplete:x.incomplete.map(v=>v.id),overflow:document.documentElement.scrollWidth-innerWidth}});assert.equal(a.overflow,0,name);assert.equal(a.violations.length,0,JSON.stringify(a));assert.match(await page.title(),/Benchmark Heaven/);assert.equal(await page.getByRole('link',{name:'Benchmark Heaven',exact:true}).count(),1);assert.doesNotMatch(await page.locator('body').innerText(),/Model Market Comparison/);fs.writeFileSync(out+'/'+name+'-tree.txt',await page.locator('body').ariaSnapshot());checks.push({name,path,width,height,theme,title:await page.title(),...a});}
await snap('overview-light','/',1440,1000,'light');
await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Skip to main content');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement?.id),'main-content');checks.push({name:'keyboard-skip',passed:true});
await snap('overview-dark','/',1440,1000,'dark');await snap('overview-mobile','/',390,844,'light');await snap('overview-320','/',320,844,'dark');
await snap('radar-mobile-dark','/radar',390,844,'dark');await snap('compare-dark','/compare',1440,1000,'dark');
await page.getByRole('combobox',{name:'Model C',exact:true}).selectOption('gpt-5.6-terra::high');await page.waitForFunction(()=>document.querySelector('[aria-label="Chart legend"]')?.children.length===3);checks.push({name:'three-model-selection',passed:true});
await snap('footer-light','/about',1440,1000,'light');await page.locator('footer').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/footer-light.png'});
for (const path of ['/','/compare','/benchmarks','/radar','/charts','/scatter','/providers','/provider-explorer','/gateways','/eu','/about']){const r=await fetch(base+path);assert.equal(r.status,200,path);const html=await r.text();assert.ok(!html.includes('Model Market Comparison'));checks.push({path,status:r.status,oldBrandAbsent:true});}
await page.goto(base);const metadata=await page.evaluate(()=>({og:document.querySelector('meta[property="og:image"]')?.content,site:document.querySelector('meta[property="og:site_name"]')?.content,twitter:document.querySelector('meta[name="twitter:card"]')?.content,icon:document.querySelector('link[rel="icon"]')?.getAttribute('href'),apple:document.querySelector('link[rel="apple-touch-icon"]')?.getAttribute('href')}));assert.equal(metadata.og,'https://benchmarkheaven.com/brand/og-image.png');assert.equal(metadata.site,'Benchmark Heaven');assert.equal(metadata.twitter,'summary_large_image');
for(const p of ['/icon.svg','/apple-icon.png','/brand/og-image.png','/brand/wordmark.svg','/brand/variants.svg','/manifest.webmanifest']){const r=await fetch(base+p);assert.equal(r.status,200,p);checks.push({path:p,status:r.status,type:r.headers.get('content-type')});}
await page.setViewportSize({width:1200,height:660});await page.goto(base+'/brand/variants.svg');await page.screenshot({path:out+'/variants.png'});
await page.setViewportSize({width:1000,height:440});await page.goto(base+'/about');await page.waitForLoadState('networkidle');await page.setContent(`<html lang="en"><body style="margin:0;padding:32px;background:#f5f8fc;font:16px Arial;color:#182639"><h1>Observatory — production assets</h1><img alt="Benchmark Heaven" width="900" height="180" src="${base}/brand/wordmark.svg"><div style="display:flex;align-items:center;gap:40px;margin-top:32px">${[16,32,64].map(w=>`<div><img alt="" width="${w}" height="${w}" src="${base}/icon.svg"><p>${w} px</p></div>`).join('')}<img alt="Touch icon" width="80" height="80" src="${base}/apple-icon.png"></div></body></html>`);await page.waitForLoadState('networkidle');assert.ok(await page.locator('img').evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth>0)));await page.screenshot({path:out+'/assets.png'});
if(errors.length)console.log(JSON.stringify(errors));assert.equal(errors.length,0);fs.writeFileSync(out+'/checks.json',JSON.stringify({at:new Date().toISOString(),base,metadata,checks,errors},null,2)+'\n');await browser.close();console.log('Brand pages, assets, metadata, 7 axe states, 320px reflow, keyboard skip and model selection passed');
