import Link from 'next/link';
import type { BenchmarkView } from '../lib/benchmark-view.mjs';
import { AnomalySummary, SourceScore } from './BenchmarkEvidence';
import { CompositeNote } from './CompositeNote';
export function BenchmarkSheet({ view, modelId }: { view: BenchmarkView; modelId: string }) {
  const axes = view.axes.filter((a) => a.scores.some((r) => r.modelId === modelId));
  const versions = new Set(axes.filter((a) => !a.id.startsWith('aa_coding_index') && !a.id.startsWith('aa_intelligence_index') && !a.id.startsWith('frontend') && !a.id.startsWith('fullstack')).map((a) => a.benchmarkId)).size;
  const categories = [...new Set(axes.map((a) => a.category))].sort();
  const absent = [...new Map(view.axes.filter((a) => !axes.some((present) => present.benchmarkId === a.benchmarkId)).map((a) => [a.benchmarkId, a])).values()];
  return <section id="benchmark-sheet" className="mt-8 scroll-mt-6 space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="bh-eyebrow">MODEL EVIDENCE</p><h2 className="text-2xl font-semibold">Benchmark sheet</h2><p className="bh-muted mt-2 text-sm">{versions} / {view.registryCount} registered benchmark versions covered · {axes.reduce((n, a) => n + a.scores.length, 0)} observations including existing index snapshots.</p></div><Link className="bh-button" href={`/compare?model=${encodeURIComponent(modelId)}`}>Compare this model ↗</Link></div>
    <CompositeNote date={view.legacyDate} />
    <div className="bh-panel p-5"><AnomalySummary view={view} modelId={modelId} /></div>
    {categories.map((category) => <section key={category} className="bh-panel overflow-hidden p-5"><h3 className="mb-4 text-lg font-semibold">{category}</h3><div className="bh-table-wrap overflow-x-auto" tabIndex={0} role="region" aria-label={`${category} benchmark observations`}><table className="bh-table w-full text-sm"><caption className="sr-only">{category}: every observation for this exact model configuration</caption><thead><tr><th scope="col">Benchmark / version</th><th scope="col">Evaluation group</th><th scope="col">Score / provenance</th></tr></thead><tbody>{axes.filter((a) => a.category === category).flatMap((a) => a.scores.map((r) => <tr key={r.id}><th scope="row" className="min-w-52 align-top text-left font-medium"><Link className="text-accent hover:underline" href={`/benchmarks?benchmark=${encodeURIComponent(a.benchmarkId)}`}>{a.name}</Link><p className="bh-muted mt-1 text-xs">Version {a.version}</p></th><td className="max-w-sm align-top text-xs bh-muted">{a.cohort}<p className="mt-2">{a.description}</p></td><td className="min-w-60 align-top"><SourceScore view={view} axis={a} row={r} /></td></tr>))}</tbody></table></div></section>)}
    {!axes.length && <div className="bh-empty">No verified benchmark observation is attached to this exact configuration yet. Provider pricing can still be available.</div>}
    <details className="bh-panel p-5"><summary className="font-medium">Missing coverage · {absent.length} benchmark versions</summary><p className="bh-muted my-3 text-sm">No result does not mean a zero, or that the model was never tested. Collection failures and disputed versions retain their distinct status.</p><ul className="grid gap-3 md:grid-cols-2">{absent.map((a) => { const missing = view.missing.find((m) => m.model_id === modelId && m.benchmark_id === a.benchmarkId); return <li key={a.benchmarkId} className="rounded border border-line p-3 text-sm"><Link className="text-accent" href={`/benchmarks?benchmark=${encodeURIComponent(a.benchmarkId)}`}>{a.name} · {a.version}</Link><p className="bh-muted mt-1 text-xs">{missing ? `${missing.status.replaceAll('_', ' ')}: ${missing.reason}` : a.collection && a.collection.status !== 'collected' ? `${a.collection.status.replaceAll('_', ' ')}: ${a.collection.reason}` : 'Unknown: no published result matched to this configuration.'}</p></li>; })}</ul></details>
  </section>;
}
