"use client";
import {useId,useMemo,useState} from "react";
import type {V16Page,V16Weights,V16PageProfile} from "../lib/jevbench-page-v16.mjs";
import type {V16ProjectedRow} from "../lib/jevbench-registry-v16.mjs";
import {v16CapView,v16MeasuredLabel,v16TrafficZone} from "../lib/jevbench-presentation-v16.mjs";
import {Radar,type Spoke} from "./JevRadars";
const axes=["intelligence","calibration","speed","cost"] as const;
const num=(n:number|null|undefined)=>n==null?"Unavailable":n.toFixed(2);
// Only coordinates are clipped; stored values/tables/tooltips stay raw.
const radarValue=(v:number|null)=>v===null?null:Math.max(0,Math.min(100,v));
const priceRole={served_cost:"Served cost",developer_api_list:"Developer API list-price scenario",base_model_reference:"Base-model reference"};
function CellRadar({profile,kind,descriptors,id,name}:{profile:V16PageProfile;kind:"topics"|"usecases";descriptors:V16Page['projection']['category_descriptors']['topics'];id:string;name:string}) {
 const spokes:Spoke[]=descriptors.map(d=>{const c=profile[kind][d.key];return {key:d.key,lines:[d.label],values:[radarValue(c.competence)],texts:[`${num(c.competence)} · n=${c.n}${c.low_n?" · low n":""}`],thin:[c.low_n||c.competence===null],tip:d.covers};});
 return <article className="rounded border border-line p-3" data-bh-jev16-profile-kind={profile.kind}>
  <h4>{name} · {kind==="topics"?"Topics":"Use cases"}</h4>
  <p className="bh-muted text-xs">{profile.kind} · {profile.revision} · measured {profile.measured_on} · {profile.scope} · {profile.metric}</p>
  <Radar spokes={spokes} series={[{name,stroke:"rgb(var(--accent))",dashed:false,square:false}]} size={{w:560,h:520,r:145}} id={id} title={`${name} ${kind}`} desc="Stored competence; missing/low-n cells omitted. Cohorts are not equated." />
  <details><summary>Stored values and sample counts</summary><table><thead><tr><th>Category</th><th>Competence</th><th>n</th></tr></thead><tbody>{descriptors.map(d=><tr key={d.key}><th>{d.label}</th><td>{num(profile[kind][d.key].competence)}</td><td>{profile[kind][d.key].n}{profile[kind][d.key].low_n?" (low n)":""}</td></tr>)}</tbody></table></details>
 </article>;
}
function Language({row,id}:{row:V16ProjectedRow;id:string}) {
 const [split,setSplit]=useState<"public"|"sealed">("public");
 const m=row.language;
 if(!m)return <p>Language view unavailable for this model.</p>;
 const cells=m[split],spokes:Spoke[]=Object.entries(cells).map(([key,c])=>({key,lines:[key],values:[radarValue(c.cc)],texts:[`${num(c.cc)} · ${c.n}/${c.expected_n} · ${c.measured_on??"date unknown"}`],thin:[c.low_n||c.status!=="measured"||c.cc===null],tip:c.reason??undefined}));
 return <article className="rounded border border-line p-3"><h4>{row.display} · Language view</h4><label>Language split <select value={split} onChange={e=>setSplit(e.target.value as "public"|"sealed")}><option value="public">Public supplement</option><option value="sealed">Sealed supplement</option></select></label>
  <p className="bh-muted text-xs">uc1.1 Choice only; separately dated diagnostics, outside Composite. Missing cells are unavailable. API sealed supplement stays unavailable.</p>
  <Radar spokes={spokes} series={[{name:row.display,stroke:"rgb(var(--accent))",dashed:false,square:false}]} size={{w:680,h:650,r:190}} id={id} title={`${row.display} ${split} language diagnostics`} desc="Stored Choice-only competence and original supplement split; no cross-cohort equating."/>
  <details><summary>Language data and dates</summary><table><thead><tr><th>Language</th><th>CC</th><th>Accuracy</th><th>Measured/expected</th><th>Non-ok</th><th>Date/status</th></tr></thead><tbody>{Object.entries(cells).map(([key,c])=><tr key={key}><th>{key}</th><td>{num(c.cc)}</td><td>{num(c.accuracy)}</td><td>{c.n}/{c.expected_n}</td><td>{c.non_ok_n}</td><td>{c.measured_on??"Date unknown"} · {c.reason??c.status}</td></tr>)}</tbody></table></details>
  {m.carried_base&&<p className="bh-muted text-xs">Original sealed measurement retained separately: {m.carried_base.revision} · {m.carried_base.measured_on} · {m.carried_base.basis}</p>}
 </article>;
}
function CapabilityScatter({rows,reference,axis}:{rows:V16ProjectedRow[];reference:V16Page['projection']['reference'];axis:"cost"|"latency"}) {
 const baseline=axis==='cost'?reference.usd_per_1000:reference.p50_s_adjusted;
 const label=axis==='cost'?'Served cost (USD/1000)':'Measured adjusted median latency (seconds)';
 const points=rows.map(r=>({r,value:axis==='cost'?r.cost.usd_per_1000:r.speed?.p50_s_adjusted})).filter((p):p is {r:V16ProjectedRow;value:number}=>p.value!==null&&p.value!==undefined&&p.value>0&&p.r.capability!==null);
 return <svg viewBox="0 0 700 630" role="img" data-bh-jev16-capability-plot={axis} aria-label={`Capability Score versus ${label}`}>
  <path d="M70 60V550H650" fill="none" stroke="currentColor"/><text x="70" y="30">Capability Score</text><text x="160" y="610">{label} · log₂ relative to frozen reference</text>
  {[0,25,50,75,100].map(v=><text key={v} x="25" y={550-v*4.9}>{v}</text>)}
  {[-3,-2,-1,0,1,2,3].map(v=><text key={v} x={350+v*90} y="575" textAnchor="middle">{num(baseline*2**v)}</text>)}
  {points.map(({r,value})=>{const x=350+90*Math.max(-3,Math.min(3,Math.log2(value/baseline))),y=550-4.9*Math.max(0,Math.min(100,r.capability!));return <g key={r.key} data-bh-jev16-plot-model={r.key}><circle cx={x} cy={y} r="6" fill="rgb(var(--accent))"><title>{`${r.display}: ${label} ${value}, Capability ${r.capability}`}</title></circle><text x={x+8} y={y} fontSize="10">{r.display}</text></g>;})}
 </svg>;
}
function Scatter({rows,reference,mode,angle}:{rows:V16ProjectedRow[];reference:V16Page['projection']['reference'];mode:"2d"|"3d";angle:number}) {
 const rad=angle*Math.PI/180;
 const points=rows.filter(r=>r.cost.cost_rank_eligible&&r.cost.admission_sha256&&r.cost.usd_per_1000!==null&&r.speed?.p50_s_adjusted!==null&&r.speed?.p50_s_adjusted!==undefined&&r.speed.n!>0&&r.capability!==null).map(r=>{
  const x=Math.max(-3,Math.min(3,Math.log2(Math.max(.125,r.cost.usd_per_1000!/reference.usd_per_1000)))),y=Math.max(-3,Math.min(3,Math.log2(Math.max(.125,r.speed!.p50_s_adjusted!/reference.p50_s_adjusted)))),z=r.capability!/100*3;
  return {r,x:mode==="3d"?350+80*(x*Math.cos(rad)-z*Math.sin(rad)):350+x*90,y:mode==="3d"?330+y*65-35*(x*Math.sin(rad)+z*Math.cos(rad)):330+y*80};
 });
 return <svg viewBox="0 0 700 630" role="img" aria-label={`${mode} cost and measured adjusted median latency, capability ${mode==='3d'?'height':'bubble size'}`}><path d="M60 60V560H650" fill="none" stroke="currentColor"/><text x="260" y="610">Served cost / frozen reference (log₂)</text><text x="15" y="30">Measured median / reference (log₂)</text>{points.map(({r,x,y})=><g key={r.key}><circle cx={Number(x.toFixed(3))} cy={Number(y.toFixed(3))} r={mode==='3d'?6:4+r.capability!/8} fill="rgb(var(--accent))" fillOpacity=".5"><title>{`${r.display}: cost ${r.cost.usd_per_1000}, median ${r.speed!.p50_s_adjusted}, Capability ${r.capability}`}</title></circle><text x={Number((x+8).toFixed(3))} y={Number(y.toFixed(3))} fontSize="10">{r.display}</text></g>)}</svg>;
}
/** Complete SOURCE candidate. No route imports it. Server parent supplies exact
 * admitted aggregate contracts; this component never evaluates a scorer. */
export function JevBenchV16ReleasePage({page,allowFixture=false}:{page:V16Page;allowFixture?:boolean}) {
 const {projection:p,manifest:m,profiles}=page,id=useId();
 const [caps,setCaps]=useState({costFactor:2,latencyFactor:2}),[search,setSearch]=useState(""),[lane,setLane]=useState("all");
 const [mode,setMode]=useState<"2d"|"3d">("2d"),[angle,setAngle]=useState(30);
 const [scenario,setScenario]=useState(m.official_scenario),[unsupported,setUnsupported]=useState(false);
 const view=useMemo(()=>v16CapView(p,caps,{allowFixture}),[p,caps,allowFixture]);
 const matches=(r:V16ProjectedRow)=>(lane==='all'||r.registration?.lane===lane)&&`${r.key} ${r.display}`.toLowerCase().includes(search.toLowerCase());
 const visible=view.rows.filter(x=>matches(x.row)),ranked=p.rows.filter(r=>r.ranked);
 const [a,setA]=useState(ranked[0]?.key??""),[b,setB]=useState(ranked[1]?.key??ranked[0]?.key??"");
 const pair=[a,b].map(k=>p.rows.find(r=>r.key===k)).filter((r):r is V16ProjectedRow=>!!r);
 const selected=m.scenarios.find(s=>s.id===scenario)!;
 const chooseWeight=(axis:keyof V16Weights,value:number)=>{const weights={...selected.weights,[axis]:value};const match=m.scenarios.find(s=>axes.every(k=>s.weights[k]===weights[k]));if(match){setScenario(match.id);setUnsupported(false);}else setUnsupported(true);};
 const composite=[...ranked].filter(matches).sort((a,b)=>selected.scores[b.key]-selected.scores[a.key]||a.key.localeCompare(b.key));
 return <main className="mx-auto max-w-7xl space-y-12 px-4 py-8" data-bh-jev16-release-source>
  <header><h1 className="text-3xl font-bold">JevBench v1.6.0</h1><p>Capability, price and measured speed · generated {m.generated_on}</p><nav className="flex flex-wrap gap-4"><a href="#jev16-capability">Capability</a><a href="#jev16-bubbles">Cost & speed</a><a href="#jev16-composite">Composite</a><a href="#jev16-compare">Compare</a><a href="#jev16-grid">Full table</a><a href="#jev16-method">Method</a><a href="#jev16-history">Revisions</a></nav></header>
  <div className="flex flex-wrap gap-4"><label>Find a model <input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Serving <select value={lane} onChange={e=>setLane(e.target.value)}><option value="all">All</option><option value="selfhosted">Self-hosted</option><option value="api">API</option></select></label></div>
  <section id="jev16-capability"><h2 className="text-2xl font-bold">Capability Score</h2><p>Mean of Intelligence and Calibration inside admitted cost and actual measured adjusted median caps. {view.official?"Official 2× envelope":"Custom caps — not the official ranking"}.</p>
   {([['costFactor','Cost cap'],['latencyFactor','Median latency cap']] as const).map(([k,label])=><label className="block my-3" key={k}>{label}: {caps[k]===Infinity?'off':`${caps[k]}×`} <input aria-label={label} type="range" min="1" max="10" step=".25" value={caps[k]===Infinity?10:caps[k]} onChange={e=>setCaps({...caps,[k]:Number(e.target.value)})}/><button onClick={()=>setCaps({...caps,[k]:Infinity})}>Turn off {label.toLowerCase()}</button><button onClick={()=>setCaps({...caps,[k]:2})}>Reset 2×</button></label>)}
   <ol>{view.eligible.filter(x=>matches(x.row)).map((x,i)=><li key={x.row.key} className="border-t border-line py-2"><b>{i+1}. {x.row.display}</b> · {num(x.row.capability)}<span className="block h-2 bg-surface"><span className="block h-full bg-accent" style={{width:`${Math.min(100,x.row.capability??0)}%`}}/></span>{([['Cost',x.costRatio,caps.costFactor],['Median',x.latencyRatio,caps.latencyFactor]] as const).map(([label,ratio,cap])=><span key={label} className={`mr-4 block bh-tl-${v16TrafficZone(ratio,cap)}`}>{label}: {num(ratio)}× · {v16TrafficZone(ratio,cap)}<span className="block h-1 bg-surface"><span className={`block h-full bh-tl-${v16TrafficZone(ratio,cap)}`} style={{width:`${ratio===null?0:Math.min(100,Math.max(0,Math.log2(Math.max(.125,ratio)) + 3)/6*100)}%`}}/></span></span>)}</li>)}</ol>
   <details><summary>Outside the selected envelope / unranked ({visible.filter(x=>!x.eligible).length})</summary>{visible.filter(x=>!x.eligible).map(x=><p key={x.row.key}>{x.row.display}: {x.reasons.join(' ')}</p>)}</details>
  </section>
  <section id="jev16-bubbles"><h2 className="text-2xl font-bold">Cost and measured speed</h2><p>Same catalogue filters and cap selection. Missing or unadmitted costs and missing measured medians are not plotted.</p><button onClick={()=>setMode(mode==='2d'?'3d':'2d')}>{mode==='2d'?'Show 3D':'Show 2D'}</button>{mode==='3d'&&<label>Rotate <input type="range" min="0" max="360" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label>}{mode==='2d'?<div className="grid md:grid-cols-2 gap-4">{(['latency','cost'] as const).map(axis=><CapabilityScatter key={axis} axis={axis} rows={view.eligible.filter(x=>matches(x.row)).map(x=>x.row)} reference={p.reference}/>)}</div>:<Scatter rows={view.eligible.filter(x=>matches(x.row)).map(x=>x.row)} reference={p.reference} mode={mode} angle={angle}/> }</section>
  <section id="jev16-composite"><h2 className="text-2xl font-bold">Composite Score</h2><p>{scenario===m.official_scenario?'Official stored Composite':'What If — stored scorer scenario, not official ranking'}. Changing Capability caps does not recompute Composite.</p><label>Preset <select value={scenario} onChange={e=>{setScenario(e.target.value);setUnsupported(false);}}>{m.scenarios.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
   <fieldset><legend>What If weights — only source-bound scored combinations</legend>{axes.map(axis=>{const values=[...new Set(m.scenarios.map(s=>s.weights[axis]))].sort((a,b)=>a-b);return <label className="block" key={axis}>{axis}: {selected.weights[axis]} <input aria-label={`${axis} weight`} type="range" min="0" max={values.length-1} step="1" value={values.indexOf(selected.weights[axis])} onChange={e=>chooseWeight(axis,values[Number(e.target.value)])}/></label>;})}</fieldset>{unsupported&&<p role="status">That weight combination has no admitted scorer result. The previous stored scenario remains selected.</p>}
   <ol>{composite.map((row,i)=><li className="border-t border-line py-2" key={row.key}>{i+1}. {row.display} · {num(selected.scores[row.key])}<span className="block h-3 bg-surface"><span className="block h-full bg-accent" data-bh-jev16-composite-bar={row.key} data-bh-jev16-stored-score={selected.scores[row.key]} style={{width:`${Math.max(0,Math.min(100,selected.scores[row.key]))}%`}}/></span></li>)}</ol>
  </section>
  <section id="jev16-compare"><h2 className="text-2xl font-bold">Compare models</h2>{([[a,setA,'First'],[b,setB,'Second']] as const).map(([key,set,label])=><label className="mr-4" key={label}>{label} model <select value={key} onChange={e=>set(e.target.value)}>{ranked.map(r=><option key={r.key} value={r.key}>{r.display} · {r.status}</option>)}</select></label>)}
   <p>Separate radars retain each model's method, scope and measurement date. API A300+P300, local S1200+P300 and historical carry are not equated or overlaid.</p>
   <div className="grid md:grid-cols-2 gap-4">{pair.map((row,i)=><div key={`${i}-${row.key}`}><CellRadar profile={profiles[row.key]} kind="topics" descriptors={p.category_descriptors.topics} id={`${id}-${i}-topics`} name={row.display}/><CellRadar profile={profiles[row.key]} kind="usecases" descriptors={p.category_descriptors.usecases} id={`${id}-${i}-usecases`} name={row.display}/><Language row={row} id={`${id}-${i}-languages`}/></div>)}</div>
  </section>
  <section id="jev16-grid"><h2 className="text-2xl font-bold">Full catalogue and data grid</h2><p>{p.catalogue_count} catalogue entries; {ranked.length} ranked. Existing carry and unmeasured entries remain visible with their original provenance.</p><details><summary>Expand all columns ({visible.length} matching models)</summary><div className="overflow-x-auto"><table className="text-xs"><thead><tr>{['Model','Status/date','Model version/pin','Serving','Size','Context','Capability','Composite','Intelligence','Calibration','Speed','Cost','Adjusted p50','Raw p50 / p95','Price roles','Historical price','Choice / NOUL / Score','Author / repo / licence','Eligibility'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(({row:r,reasons})=><tr key={r.key}><th>{r.display}</th><td>{r.status} · {v16MeasuredLabel(r)}</td><td>{r.measurement?.model_version??'Unavailable'} / {r.measurement?.model_pin??'Unavailable'}</td><td>{r.registration?.lane??'Unavailable'} · {r.registration?.endpoint_kind??'Unavailable'} · {r.measurement?.serving.endpoint_condition??''}</td><td>Unavailable</td><td>Unavailable</td><td>{num(r.capability)}</td><td>{num(r.composite)}</td>{axes.map(k=><td key={k}>{num(r.axes[k])}</td>)}<td>{num(r.speed?.p50_s_adjusted)}</td><td>{num(r.speed?.p50_s_raw)} / {num(r.speed?.p95_s_raw)}</td><td>{r.cost.bars.map(bar=><div key={bar.role}>{priceRole[bar.role]}: {num(bar.usd_per_1000)} USD/1000 · {bar.kind}<small className="block">{bar.basis}{bar.role!=='served_cost'?' · disclosure only; no alternative hosted latency':''}</small><span className="block h-1 bg-accent" data-bh-jev16-price-striped={bar.role==='base_model_reference'?'true':undefined} style={{backgroundImage:bar.role==='base_model_reference'?'repeating-linear-gradient(135deg,transparent,transparent 3px,white 3px,white 5px)':undefined}}/></div>)}</td><td>{r.historical_price?`${num(r.historical_price.usd_per_1000)} · ${r.historical_price.kind} · ${r.historical_price.basis}`:'Unavailable'}</td><td>{r.registration?`${r.registration.support.choice} / ${r.registration.support.noul} / ${r.registration.support.score}`:'Unavailable'}</td><td>{r.registration?.author??'Unknown'} · {String(r.catalogue.repo??'Unknown')} · {String(r.catalogue.licence??'Unknown')}</td><td>{reasons.length?reasons.join(' '):'Inside selected Capability envelope'}</td></tr>)}</tbody></table></div></details></section>
  <section id="jev16-method"><h2 className="text-2xl font-bold">Method</h2>{m.method.map((paragraph,i)=><p className="my-2" key={i}>{paragraph}</p>)}<p>Sealed release subset: {m.rotation.sealed_release_count}; reserve: {m.rotation.sealed_reserve_count}; retirement after {m.rotation.retire_after_uses} uses; API cadence: once per {m.rotation.api_every_n_releases} releases. {m.rotation.disclosure}</p><p>Jev 1.13.0 frozen reference: cost {p.reference.usd_per_1000} USD/1000 and measured adjusted median {p.reference.p50_s_adjusted}s. Carry scores and prices retain their original method/date; v16 request lengths differ. List-price scenarios do not replace serving measurements.</p></section>
  <section id="jev16-history"><h2 className="text-2xl font-bold">Revision history</h2>{m.revisions.map(r=><p key={r.revision}><a href={r.href}>{r.revision}</a> · measured {r.measured_on} · {r.summary}</p>)}</section>
 </main>;
}
