import type { JevV15Artifact, JevV15System } from './jevbench-v15-preview.mjs';
export type JevV16ItemSet = { set: 'S' | 'A' | 'P'; name: string; items: number; by_type: Record<'choice' | 'noul' | 'score', number>; answered_by: string };
export type JevV16ReleaseSystem = JevV15System & { capability: number; measured_in: 'v1.6.0' | 'v1.6.1'; last_measured_on?: string | null;
  noul_decisive?: { supported: boolean; decisive_rate?: number | null; acc_among_decisive?: number | null; valid?: number } | null; v16: { lane: 'api' | 'selfhosted'; [k: string]: unknown } };
export type JevV16ReleaseArtifact = Omit<JevV15Artifact, 'systems' | 'status' | 'run_kind'> & {
  provisional: false; status: 'published'; run_kind: 'scheduled-refresh'; label: string; source_note: string; G_med_api_basis_P_vs_A: number;
  noul_method?: { applied: 'O0' | 'O1' | 'O1S'; decisive_source_sha256: string | null };
  systems: JevV16ReleaseSystem[];
  v16: { counts: Record<string, number>; equating: { offsets: Record<'I' | 'C', number>; rule: string; min_pool: number; pool_note: string; [k: string]: unknown };
    g_med_rule: string; item_sets: JevV16ItemSet[]; capability_formula: string; long_items_note?: string; [k: string]: unknown };
};
export type JevV16CategoryCell = { n: number; competence: number };
export type JevV16CategoryDescriptor = { key: string; label: string; covers: string; n: number; open: number; sealed: number; low_n: boolean };
export type JevV16Categories = { revision: 'v1.6.0' | 'v1.6.1'; provisional: false; source_results_sha256: string; min_n: number; metric: string; labelling: string; rules: string[];
  languages: JevV16CategoryDescriptor[]; lanes: Record<string, 'api' | 'selfhosted'>; lane_note: string;
  systems: Record<string, { languages: Record<string, JevV16CategoryCell>; [dim: string]: Record<string, JevV16CategoryCell> }> };
export type JevV16CarryRow = { key: string; display: string; author: string | null; class: string | null; open: string | null; licence: string | null;
  source_url?: string; repo: string | null; endpoint_kind: string | null; api_flag: boolean | null; axes: Record<'intelligence' | 'calibration' | 'speed' | 'cost', number>;
  capability: number; composite_v15: number; v156_rank: number | null; cost: { usd_per_1000: number | null; kind: string; basis: string } | null;
  speed: { p50_s_adjusted: number | null; p95_s_adjusted: number | null; n: number | null; adjustment: string | null };
  measured_revision: string; measured_label: string; date_basis: string; carried_from: 'v1.5.7'; note: string | null };
export type JevV16Carry = { kind: 'dated-carry'; revision: 'v1.6.0'; provisional: false; method: string; rule: string;
  carried_from: { revision: string; path: string; sha256: string };
  releases: { revision: string; published_on: string; main_commit: string; path: string; sha256: string }[]; rows: JevV16CarryRow[] };
export const JEVBENCH_V16_RELEASE_RESULTS: string;
export const JEVBENCH_V16_RELEASE_CATEGORIES: string;
export const JEVBENCH_V16_RELEASE_CARRY: string;
export const JEVBENCH_V161_RELEASE_RESULTS: string;
export const JEVBENCH_V161_RELEASE_CATEGORIES: string;
export const JEVBENCH_V161_RELEASE_CARRY: string;
export const JEVBENCH_V16_EXCLUDED_KEYS: string[];
export const JEVBENCH_V16_EXCLUDED_TOKEN_SHA256: string[];
export function mentionsPrivateSystem(text: string): boolean;
export function validateJevbenchV16Release(artifact: unknown, revision?: 'v1.6.0' | 'v1.6.1'): JevV16ReleaseArtifact;
export function validateJevbenchV16Carry(carry: unknown, measuredKeys: Set<string>, previous: JevV15Artifact, previousSha256: string): JevV16Carry;
export function readJevbenchV16Release(root?: string): Promise<{ artifact: JevV16ReleaseArtifact; bytes: Uint8Array; sha256: string;
  categories: JevV16Categories; categoriesSha256: string; carry: JevV16Carry; carrySha256: string }>;
export function readJevbenchV161Release(root?: string): ReturnType<typeof readJevbenchV16Release>;
