import type { JevV15Artifact, JevV15System } from './jevbench-v15-preview.mjs';
export type JevV16ItemSet = { set: 'S' | 'A' | 'P'; name: string; items: number; by_type: Record<'choice' | 'noul' | 'score', number>; answered_by: string };
export type JevV16PreviewSystem = JevV15System & { capability: number; measured_in: 'v1.6.0'; v16: { lane: 'api' | 'selfhosted'; [k: string]: unknown } };
export type JevV16PreviewArtifact = Omit<JevV15Artifact, 'systems'> & {
  provisional: true; label: string; source_note: string; G_med_api_basis_P_vs_A: number;
  systems: JevV16PreviewSystem[];
  v16: { counts: Record<string, number>; equating: { offsets: Record<'I' | 'C', number>; rule: string; min_pool: number; pool_note: string; [k: string]: unknown };
    g_med_rule: string; item_sets: JevV16ItemSet[]; capability_formula: string; [k: string]: unknown };
};
export type JevV16CategoryCell = { n: number; competence: number };
export type JevV16CategoryDescriptor = { key: string; label: string; covers: string; n: number; open: number; sealed: number; low_n: boolean };
export type JevV16Categories = { revision: 'v1.6.0'; provisional: true; min_n: number; metric: string; labelling: string; rules: string[];
  languages: JevV16CategoryDescriptor[]; lanes: Record<string, 'api' | 'selfhosted'>; lane_note: string;
  systems: Record<string, { languages: Record<string, JevV16CategoryCell>; [dim: string]: Record<string, JevV16CategoryCell> }> };
export type JevV16CarryRow = { key: string; display: string; author: string | null; class: string | null; open: string | null; licence: string | null;
  repo: string | null; endpoint_kind: string | null; api_flag: boolean | null; axes: Record<'intelligence' | 'calibration' | 'speed' | 'cost', number>;
  capability: number; composite_v15: number; v155_rank: number | null; cost: { usd_per_1000: number | null; kind: string; basis: string } | null;
  speed: { p50_s_adjusted: number | null; p95_s_adjusted: number | null; n: number | null; adjustment: string | null };
  measured_revision: string; measured_label: string; date_basis: string; carried_from: 'v1.5.5'; note: string | null };
export type JevV16Carry = { kind: 'dated-carry'; revision: 'v1.6.0'; provisional: true; method: string; rule: string;
  carried_from: { revision: string; path: string; sha256: string };
  releases: { revision: string; published_on: string; main_commit: string; path: string; sha256: string }[]; rows: JevV16CarryRow[] };
export const JEVBENCH_V16_PREVIEW_RESULTS: string;
export const JEVBENCH_V16_PREVIEW_CATEGORIES: string;
export const JEVBENCH_V16_PREVIEW_CARRY: string;
export const JEVBENCH_V16_PREVIEW_ROUTE: string;
export const JEVBENCH_V16_EXCLUDED_KEYS: string[];
export function validateJevbenchV16Preview(artifact: unknown): JevV16PreviewArtifact;
export function validateJevbenchV16Carry(carry: unknown, measuredKeys: Set<string>): JevV16Carry;
export function readJevbenchV16Preview(root?: string): Promise<{ artifact: JevV16PreviewArtifact; sha256: string;
  categories: JevV16Categories; categoriesSha256: string; carry: JevV16Carry; carrySha256: string }>;
