import type {V16MeasurementBinding} from './jevbench-registry-v16.mjs';
export type OldCarryCell={n:number;competence:number};
export type OldCarryDescriptor={key:string;label:string;covers:string;n:number;open:number;sealed:number;low_n?:boolean};
export type OriginalDateEvidence={precision:'calendar-day'|'utc-instant';value:string;timezone:'UTC'|'unknown';source_original:string;origin_receipt_sha256:string};
export type DatedOldCarryProfile={kind:'dated-old';key:string;model_version:string;model_pin:string;measurement_revision:string;measurement_method_version:string;main_measured_on:string;original_model_revision:string;measurement_date:OriginalDateEvidence;measurement_descriptor_sha256:string;origin_receipt_sha256:string;row_cohort:{n:number;open:number;sealed:number};cells:Record<'topics'|'usecases',Record<string,OldCarryCell>>;artifact_revision:string;category_method_version:'v1.5-item-count-weighted-multiple-usecase';metric:string;labelling:string;rules:string[];min_n:number;taxonomy:Record<'topics'|'usecases',OldCarryDescriptor[]>;full_cohort:{name:string;n:number;open:number;sealed:number;membership_sha256:string};comparison_basis:'OLD_UNEQUATED_NOT_CURRENT';usecase_membership:'multiple';category_split_basis:string;source_artifact_sha256:string;source_results_sha256:string;taxonomy_sha256:string;cohort_sha256:string;projection_source_sha256:string;carry_sha256:string};
export type DatedCarryArtifact={kind:'jevbench-dated-category-carry';benchmark:'JevBench';revision:'v1.6.0';fixture:boolean;generated_on:string;public_roster_sha256:string;source_artifact_sha256:string;source_results_sha256:string;taxonomy_sha256:string;cohort_sha256:string;projection_source_sha256:string;artifact_revision:string;method_version:'v1.5-item-count-weighted-multiple-usecase';metric:string;labelling:string;rules:string[];min_n:number;taxonomy:DatedOldCarryProfile['taxonomy'];full_cohort:DatedOldCarryProfile['full_cohort'];profiles:Record<string,Pick<DatedOldCarryProfile,'key'|'model_version'|'model_pin'|'measurement_revision'|'measurement_method_version'|'main_measured_on'|'original_model_revision'|'measurement_date'|'measurement_descriptor_sha256'|'origin_receipt_sha256'|'row_cohort'|'cells'>>};
export function validateDatedCarryArtifact(value:unknown):DatedCarryArtifact;
export function datedCarryForBinding(artifact:unknown,binding:V16MeasurementBinding,diagnostic:unknown,carryHash:string,publicHash:string):DatedOldCarryProfile;
export function datedCarryPageProfile(profile:DatedOldCarryProfile,row:import('./jevbench-registry-v16-carry.mjs').V16CarryProjectedRow):DatedOldCarryProfile;
