export const MIN_RUN: number;
export const RADAR_MIN_N: number;
export function presentRuns(present: boolean[]): number[][];
export function radarShape(present: boolean[]): { kind: 'polygon' | 'runs' | 'points' | 'none'; runs: number[][] };
export function radarValue(v: unknown): number | null;
export function plottable(v: unknown, thin: boolean): boolean;
export type RadarDomain = readonly [number, number];
export const RADAR_DEFAULT_DOMAIN: RadarDomain;
export const RADAR_SIGNED_DOMAIN: RadarDomain;
export function radarRadius(v: number, domain?: RadarDomain): number;
export function radarScale(domain?: RadarDomain): { signed: boolean; rings: number[]; zero: number | null; labels: number[] };
export function ringLabelPoint(v: number, geo: { cx: number; cy: number; R: number; n: number }, domain?: RadarDomain): { x: number; y: number };
export function ringLabelText(v: number): string;
export function categoryCell(cell: readonly unknown[] | null | undefined, radarMinN?: number): { value: number | null; thin: boolean; n: number | null; text: string };
export const DENSE_SPOKES: number;
export const BADGE_R: number;
export const BADGE_FONT: number;
export type RadarBox = { x0: number; x1: number; y0: number; y1: number };
export type RadarSize = { w: number; h: number; r: number };
export function fullLabelLayout(labels: { lines: string[]; value: string }[], size: RadarSize): { x: number; y: number; anchor: 'start' | 'middle' | 'end'; box: RadarBox }[];
export function numberedLayout(n: number, size: RadarSize): { w: number; h: number; r: number; cx: number; cy: number; badges: { x: number; y: number; box: RadarBox }[] };
export function labelCollisions(items: { box: RadarBox }[], w: number, h: number): { overlaps: [number, number][]; outside: number[] };
export function radarLabelMode(labels: { lines: string[]; value: string }[], size: RadarSize): 'full' | 'numbered';
export const NUMBERED_SIDE: number;
