import { previewMetadata } from '../../../lib/seo';
import { DecisionGuide } from '../../../components/DecisionBenchmarkGuide';
export const metadata = previewMetadata({ path: '/jev-models/calibration-reliability', title: 'How to measure calibration & reliability in decision models', documentTitle: 'How to measure calibration & reliability in decision models', description: 'Evaluate probability calibration, abstention, coherence and workload reliability. Learn what JevBench measures and what needs a separate test.' });
export default function CalibrationGuide() {
  return <DecisionGuide title="How to measure calibration and reliability in decision models" intro="Measure correctness and probability quality on held-out decisions, then test the confidence thresholds you will use in production. Calibration means probabilities agree with observed outcomes; reliability also requires failure handling, robustness and acceptable error costs. JevBench’s Calibration axis is one part of this evaluation.">
    <section className="space-y-3"><h2 className="text-2xl font-semibold">Keep the measurements separate</h2><p>Report accuracy or task-appropriate class metrics alongside a proper probability score such as Brier score or negative log likelihood. Inspect reliability plots and calibration error by domain and confidence range; report sample counts because small bins are noisy. A high-confidence correct answer is useful evidence, but accuracy alone does not establish calibration.</p><p>JevBench publishes its versioned distribution-quality Calibration axis. That normalized score is not interchangeable with another benchmark&apos;s ECE, NLL or Brier score. Read the <a className="text-accent underline" href="/jev-models/methodology">scorer and method</a> before interpreting it.</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-semibold">Evaluate abstention and failure cost</h2><p>At each proposed confidence threshold, measure the fraction of decisions accepted (coverage) and their error rate (selective risk). Count refusals, invalid distributions, timeouts and unsupported classes. Test routing to a stronger model or a human with your own costs for false positives, false negatives and escalations. Select thresholds on validation data, then evaluate once on a separate test set.</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-semibold">Add coherence and robustness checks</h2><p>Check that probabilities follow option reordering, negation and equivalent wording. Internal coherence does not imply correct answers: a model can be consistently wrong. The independent <a className="text-accent underline" href="https://github.com/JevBench/jevbench">metamorphic coherence JevBench</a> complements our accuracy and serving measurements. <a className="text-accent underline" href="https://forecastbench.org/docs/">ForecastBench</a> is relevant when the decisions are predictions about future outcomes.</p><p>Retest under realistic class imbalance, new domains and input changes. Record model pins, dataset versions, measurement dates, latency percentiles and cost assumptions. A benchmark shortlist helps choose candidates; it cannot certify your workload.</p></section>
  </DecisionGuide>;
}
