import { previewMetadata } from '../../../lib/seo';
import { DecisionGuide } from '../../../components/DecisionBenchmarkGuide';
export const metadata = previewMetadata({ path: '/jev-models/evaluate-alternatives', title: 'How to evaluate Jev-compatible decision model alternatives', documentTitle: 'How to evaluate Jev-compatible decision model alternatives', description: 'Compare Jev-compatible alternatives with held-out typed decisions, probability calibration, serving budgets, model pins and clear failure rules.' });
export default function AlternativesEvaluation() {
  return <DecisionGuide title="How to evaluate Jev-compatible alternatives" intro="Evaluate Jev-compatible alternatives on the same typed decisions and failure rules, with pinned model versions and disclosed runtime settings. Use JevBench to shortlist candidates by Capability and serving budget, then test probability calibration, abstention and error costs on your own held-out workload.">
    <section className="space-y-3"><h2 className="text-2xl font-semibold">Which Jev-compatible models perform best?</h2><p>The answer depends on your workload and budget. The <a className="text-accent underline" href="/jev-models">live open-weights leaderboard</a> identifies the current Capability leaders; the <a className="text-accent underline" href="/jev-models/api">hosted API leaderboard</a> compares endpoints. Read eligibility, measurement dates, confidence intervals and ties. This guide avoids copying a ranking that would become stale.</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-semibold">A repeatable evaluation</h2><ol className="list-decimal space-y-3 pl-6"><li>Define state, answer options and the probabilities your application needs. Verify native typed-output support; a prose answer parsed into a label is a different adapter.</li><li>Freeze a representative held-out set, labels, scoring rules and cost assumptions. Keep training, calibration and test splits separate.</li><li>Pin weights or the hosted model version where possible. Record endpoint, quantization, hardware, prompt/adapter and measurement dates.</li><li>Score correctness, probability quality, coverage and failures with identical rules. Compare measured latency and USD per 1,000 decisions under the same serving conditions.</li><li>Validate acceptance thresholds and escalation policies against real error costs. Run a separate test for unseen domains and operational failures.</li></ol><p>Review the <a className="text-accent underline" href="/jev-models/alternatives">alternatives inventory</a> and <a className="text-accent underline" href="/jev-models/how-to-choose">selection guide</a> for licenses and deployment constraints.</p></section>
  </DecisionGuide>;
}
